FROM node:18-alpine

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install

COPY . .

EXPOSE 3000

# In dev mode, Next.js hot reload is triggered by 'pnpm dev' from docker-compose
CMD ["pnpm", "dev"]
